#define Exif.GPSInfo.GPSVersionID 0x0000                   /* GPSInfoByteIndicates the version of <GPSInfoIFD>. The version is given as 2.0.0.0. This tag is mandatory when <GPSInfo> tag is present. (Note: The <GPSVersionID> tag is given in bytes, unlike the <ExifVersion> tag. When the version is 2.0.0.0, the tag value is 02000000.H). */                  
#define Exif.Iop.InteroperabilityIndex 0x0001              /* IopAsciiIndicates the identification of the Interoperability rule. Use "R98" for stating ExifR98 Rules. Four bytes used including the termination code (NULL). see the separate volume of Recommended Exif Interoperability Rules (ExifR98) for other tags used for ExifR98. */                       
#define Exif.GPSInfo.GPSLatitudeRef 0x0001                 /* GPSInfoAsciiIndicates whether the latitude is north or south latitude. The ASCII value 'N' indicates north latitude, and 'S' is south latitude. */                    
#define Exif.GPSInfo.GPSLatitude 0x0002                    /* GPSInfoRationalIndicates the latitude. The latitude is expressed as three RATIONAL values giving the degrees, minutes, and seconds, respectively. When degrees, minutes and seconds are expressed, the format is dd/1,mm/1,ss/1. When degrees and minutes are used and, for example, fractions of minutes are given up to two decimal places, the format is dd/1,mmmm/100,0/1. */                 
#define Exif.Iop.InteroperabilityVersion 0x0002            /* IopUndefinedInteroperability version */                         
#define Exif.GPSInfo.GPSLongitudeRef 0x0003                /* GPSInfoAsciiIndicates whether the longitude is east or west longitude. ASCII 'E' indicates east longitude, and 'W' is west longitude. */                                                          
#define Exif.GPSInfo.GPSLongitude 0x0004                   /* GPSInfoRationalIndicates the longitude. The longitude is expressed as three RATIONAL values giving the degrees, minutes, and seconds, respectively. When degrees, minutes and seconds are expressed, the format is ddd/1,mm/1,ss/1. When degrees and minutes are used and, for example, fractions of minutes are given up to two decimal places, the format is ddd/1,mmmm/100,0/1. */                  
#define Exif.GPSInfo.GPSAltitudeRef 0x0005                 /* GPSInfoByteIndicates the altitude used as the reference altitude. If the reference is sea level and the altitude is above sea level, 0 is given. If the altitude is below sea level, a value of 1 is given and the altitude is indicated as an absolute value in the GSPAltitude tag. The reference unit is meters. Note that this tag is BYTE type, unlike other reference tags. */                    
#define Exif.GPSInfo.GPSAltitude 0x0006                    /* GPSInfoRationalIndicates the altitude based on the reference in GPSAltitudeRef. Altitude is expressed as one RATIONAL value. The reference unit is meters. */                 
#define Exif.GPSInfo.GPSTimeStamp 0x0007                   /* GPSInfoRationalIndicates the time as UTC (Coordinated Universal Time). <TimeStamp> is expressed as three RATIONAL values giving the hour, minute, and second (atomic clock). */                  
#define Exif.GPSInfo.GPSSatellites 0x0008                  /* GPSInfoAsciiIndicates the GPS satellites used for measurements. This tag can be used to describe the number of satellites, their ID number, angle of elevation, azimuth, SNR and other information in ASCII notation. The format is not specified. If the GPS receiver is incapable of taking measurements, value of the tag is set to NULL. */                   
#define Exif.GPSInfo.GPSStatus 0x0009                      /* GPSInfoAsciiIndicates the status of the GPS receiver when the image is recorded. "A" means measurement is in progress, and "V" means the measurement is Interoperability. */               
#define Exif.GPSInfo.GPSMeasureMode 0x000a                 /* GPSInfoAsciiIndicates the GPS measurement mode. "2" means two-dimensional measurement and "3" means three-dimensional measurement is in progress. */                    
#define Exif.Image.ProcessingSoftware 0x000b               /* ImageAsciiThe name and version of the software used to post-process the picture. */                      
#define Exif.GPSInfo.GPSDOP 0x000b                         /* GPSInfoRationalIndicates the GPS DOP (data degree of precision). An HDOP value is written during two-dimensional measurement, and PDOP during three-dimensional measurement. */            
#define Exif.GPSInfo.GPSSpeedRef 0x000c                    /* GPSInfoAsciiIndicates the unit used to express the GPS receiver speed of movement. "K" "M" and "N" represents kilometers per hour, miles per hour, and knots. */                 
#define Exif.GPSInfo.GPSSpeed 0x000d                       /* GPSInfoRationalIndicates the speed of GPS receiver movement. */              
#define Exif.GPSInfo.GPSTrackRef 0x000e                    /* GPSInfoAsciiIndicates the reference for giving the direction of GPS receiver movement. "T" denotes true direction and "M" is magnetic direction. */                 
#define Exif.GPSInfo.GPSTrack 0x000f                       /* GPSInfoRationalIndicates the direction of GPS receiver movement. The range of values is from 0.00 to 359.99. */              
#define Exif.GPSInfo.GPSImgDirectionRef 0x0010             /* GPSInfoAsciiIndicates the reference for giving the direction of the image when it is captured. "T" denotes true direction and "M" is magnetic direction. */                        
#define Exif.GPSInfo.GPSImgDirection 0x0011                /* GPSInfoRationalIndicates the direction of the image when it was captured. The range of values is from 0.00 to 359.99. */                                                          
#define Exif.GPSInfo.GPSMapDatum 0x0012                    /* GPSInfoAsciiIndicates the geodetic survey data used by the GPS receiver. If the survey data is restricted to Japan, the value of this tag is "TOKYO" or "WGS-84". */                 
#define Exif.GPSInfo.GPSDestLatitudeRef 0x0013             /* GPSInfoAsciiIndicates whether the latitude of the destination point is north or south latitude. The ASCII value "N" indicates north latitude, and "S" is south latitude. */                        
#define Exif.GPSInfo.GPSDestLatitude 0x0014                /* GPSInfoRationalIndicates the latitude of the destination point. The latitude is expressed as three RATIONAL values giving the degrees, minutes, and seconds, respectively. If latitude is expressed as degrees, minutes and seconds, a typical format would be dd/1,mm/1,ss/1. When degrees and minutes are used and, for example, fractions of minutes are given up to two decimal places, the format would be dd/1,mmmm/100,0/1. */                     
#define Exif.GPSInfo.GPSDestLongitudeRef 0x0015            /* GPSInfoAsciiIndicates whether the longitude of the destination point is east or west longitude. ASCII "E" indicates east longitude, and "W" is west longitude. */                         
#define Exif.GPSInfo.GPSDestLongitude 0x0016               /* GPSInfoRationalIndicates the longitude of the destination point. The longitude is expressed as three RATIONAL values giving the degrees, minutes, and seconds, respectively. If longitude is expressed as degrees, minutes and seconds, a typical format would be ddd/1,mm/1,ss/1. When degrees and minutes are used and, for example, fractions of minutes are given up to two decimal places, the format would be ddd/1,mmmm/100,0/1. */                      
#define Exif.GPSInfo.GPSDestBearingRef 0x0017              /* GPSInfoAsciiIndicates the reference used for giving the bearing to the destination point. "T" denotes true direction and "M" is magnetic direction. */                       
#define Exif.GPSInfo.GPSDestBearing 0x0018                 /* GPSInfoRationalIndicates the bearing to the destination point. The range of values is from 0.00 to 359.99. */                    
#define Exif.GPSInfo.GPSDestDistanceRef 0x0019             /* GPSInfoAsciiIndicates the unit used to express the distance to the destination point. "K", "M" and "N" represent kilometers, miles and knots. */                        
#define Exif.GPSInfo.GPSDestDistance 0x001a                /* GPSInfoRationalIndicates the distance to the destination point. */                     
#define Exif.GPSInfo.GPSProcessingMethod 0x001b            /* GPSInfoUndefinedA character string recording the name of the method used for location finding. The first byte indicates the character code used, and this is followed by the name of the method. */                         
#define Exif.GPSInfo.GPSAreaInformation 0x001c             /* GPSInfoUndefinedA character string recording the name of the GPS area. The first byte indicates the character code used, and this is followed by the name of the GPS area. */                        
#define Exif.GPSInfo.GPSDateStamp 0x001d                   /* GPSInfoAsciiA character string recording date and time information relative to UTC (Coordinated Universal Time). The format is "YYYY:MM:DD.". */                  
#define Exif.GPSInfo.GPSDifferential 0x001e                /* GPSInfoShortIndicates whether differential correction is applied to the GPS receiver. */                     
#define Exif.Image.NewSubfileType 0x00fe                   /* ImageLongA general indication of the kind of data contained in this subfile. */                  
#define Exif.Image.SubfileType 0x00ff                      /* ImageShortA general indication of the kind of data contained in this subfile. This field is deprecated. The NewSubfileType field should be used instead. */               
#define Exif.Image.ImageWidth 0x0100                       /* ImageLongThe number of columns of image data, equal to the number of pixels per row. In JPEG compressed data a JPEG marker is used instead of this tag. */              
#define Exif.Image.ImageLength 0x0101                      /* ImageLongThe number of rows of image data. In JPEG compressed data a JPEG marker is used instead of this tag. */               
#define Exif.Image.BitsPerSample 0x0102                    /* ImageShortThe number of bits per image component. In this standard each component of the image is 8 bits, so the value for this tag is 8. See also <SamplesPerPixel>. In JPEG compressed data a JPEG marker is used instead of this tag. */                 
#define Exif.Image.Compression 0x0103                      /* ImageShortThe compression scheme used for the image data. When a primary image is JPEG compressed, this designation is not necessary and is omitted. When thumbnails use JPEG compression, this tag value is set to 6. */               
#define Exif 0x0106.Iand is omitted. See also <RowsPerStrip> and <StripByteCounts>. */
#define Exif.Image.Orientation 0x0112                      /* ImageShortThe image orientation viewed in terms of rows and columns. */               
#define Exif.Image.SamplesPerPixel 0x0115                  /* ImageShortThe number of components per pixel. Since this standard applies to RGB and YCbCr images, the value set for this tag is 3. In JPEG compressed data a JPEG marker is used instead of this tag. */                   
#define Exif.Image.RowsPerStrip 0x0116                     /* ImageLongThe number of rows per strip. This is the number of rows in the image of one strip when an image is divided into strips. With JPEG compressed data this designation is not needed and is omitted. See also <StripOffsets> and <StripByteCounts>. */                
#define Exif.Image.StripByteCounts 0x0117                  /* ImageLongThe total number of bytes in each strip. With JPEG compressed data this designation is not needed and is omitted. */                                                        
#define Exif.Image.XResolution 0x011a                      /* ImageRationalThe number of pixels per <ResolutionUnit> in the <ImageWidth> direction. When the image resolution is unknown, 72 [dpi] is designated. */               
#define Exif.Image.YResolution 0x011b                      /* ImageRationalThe number of pixels per <ResolutionUnit> in the <ImageLength> direction. The same value as <XResolution> is designated. */                                                    
#define Exif.Image.PlanarConfiguration 0x011c              /* ImageShortIndicates whether pixel components are recorded in a chunky or planar format. In JPEG compressed files a JPEG marker is used instead of this tag. If this field does not exist, the TIFF default of 1 (chunky) is assumed. */                       
#define Exif.Image.GrayResponseUnit 0x0122                 /* ImageShortThe precision of the information contained in the GrayResponseCurve. */                    
#define Exif.Image.GrayResponseCurve 0x0123                /* ImageShortFor grayscale data, the optical density of each possible pixel value. */                     
#define Exif.Image.T4Options 0x0124                        /* ImageLongT.4-encoding options. */             
#define Exif.Image.T6Options 0x0125                        /* ImageLongT.6-encoding options. */             
#define Exif.Image.ResolutionUnit 0x0128                   /* ImageShortThe unit for measuring <XResolution> and <YResolution>. The same unit is used for both <XResolution> and <YResolution>. If the image resolution is unknown, 2 (inches) is designated. */                  
#define Exif.Image.TransferFunction 0x012d                 /* ImageShortA transfer function for the image, described in tabular style. Normally this tag is not necessary, since color space is specified in the color space information tag (<ColorSpace>). */                    
#define Exif.Image.Software 0x0131                         /* ImageAsciiThis tag records the name and version of the software or firmware of the camera or image input device used to generate the image. The detailed format is not specified, but it is recommended that the example shown below be followed. When the field is left blank, it is treated as unknown. */            
#define Exif.Image.DateTime 0x0132                         /* ImageAsciiThe date and time of image creation. In Exif standard, it is the date and time the file was changed. */            
#define Exif.Image.Artist 0x013b                           /* ImageAsciiThis tag records the name of the camera owner, photographer or image creator. The detailed format is not specified, but it is recommended that the information be written as in the example below for ease of Interoperability. When the field is left blank, it is treated as unknown. Ex.) "Camera owner, John Smith; Photographer, Michael Brown; Image creator, Ken James" */          
#define Exif.Image.HostComputer 0x013c                     /* ImageAsciiThis tag records information about the host computer used to generate the image. */                
#define Exif.Image.Predictor 0x013d                        /* ImageShortA predictor is a mathematical operator that is applied to the image data before an encoding scheme is applied. */             
#define Exif.Image.WhitePoint 0x013e                       /* ImageRationalThe chromaticity of the white point of the image. Normally this tag is not necessary, since color space is specified in the colorspace information tag (<ColorSpace>). */              
#define Exif.Image.PrimaryChromaticities 0x013f            /* ImageRationalThe chromaticity of the three primary colors of the image. Normally this tag is not necessary, since colorspace is specified in the colorspace information tag (<ColorSpace>). */                         
#define Exif.Image.ColorMap 0x0140                         /* ImageShortA color map for palette color images. This field defines a Red-Green-Blue color map (often called a lookup table) for palette-color images. In a palette-color image, a pixel value is used to index into an RGB lookup table. */            
#define Exif.Image.HalftoneHints 0x0141                    /* ImageShortThe purpose of the HalftoneHints field is to convey to the halftone function the range of gray levels within a colorimetrically-specified image that should retain tonal detail. */                 
#define Exif.Image.TileWidth 0x0142                        /* ImageShortThe tile width in pixels. This is the number of columns in each tile. */             
#define Exif.Image.TileLength 0x0143                       /* ImageShortThe tile length (height) in pixels. This is the number of rows in each tile. */              
#define Exif.Image.TileOffsets 0x0144                      /* ImageShortFor each tile, the byte offset of that tile, as compressed and stored on disk. The offset is specified with respect to the beginning of the TIFF file. Note that this implies that each tile has a location independent of the locations of other tiles. */               
#define Exif.Image.TileByteCounts 0x0145                   /* ImageShortFor each tile, the number of (compressed) bytes in that tile. See TileOffsets for a description of how the byte counts are ordered. */                  
#define Exif.Image.SubIFDs 0x014a                          /* ImageLongDefined by Adobe Corporation to enable TIFF Trees within a TIFF file. */           
#define Exif.Image.InkSet 0x014c                           /* ImageShortThe set of inks used in a separated (PhotometricInterpretation=5) image. */          
#define Exif.Image.InkNames 0x014d                         /* ImageAsciiThe name of each ink used in a separated (PhotometricInterpretation=5) image. */            
#define Exif.Image.NumberOfInks 0x014e                     /* ImageShortThe number of inks. Usually equal to SamplesPerPixel, unless there are extra samples. */                
#define Exif.Image.DotRange 0x0150                         /* ImageByteThe component values that correspond to a 0% dot and 100% dot. */            
#define Exif.Image.TargetPrinter 0x0151                    /* ImageAsciiA description of the printing environment for which this separation is intended. */                 
#define Exif.Image.ExtraSamples 0x0152                     /* ImageShortSpecifies that each pixel has m extra components whose interpretation is defined by one of the values listed below. */                                                     
#define Exif.Image.SampleFormat 0x0153                     /* ImageShortThis field specifies how to interpret each data sample in a pixel. */                
#define Exif.Image.SMinSampleValue 0x0154                  /* ImageShortThis field specifies the minimum sample value. */                   
#define Exif.Image.SMaxSampleValue 0x0155                  /* ImageShortThis field specifies the maximum sample value. */                   
#define Exif.Image.TransferRange 0x0156                    /* ImageShortExpands the range of the TransferFunction */                 
#define Exif.Image.ClipPath 0x0157                         /* ImageByteA TIFF ClipPath is intended to mirror the essentials of PostScript's path creation functionality. */            
#define Exif.Image.XClipPathUnits 0x0158                   /* ImageSShortThe number of units that span the width of the image, in terms of integer ClipPath coordinates. */                  
#define Exif.Image.YClipPathUnits 0x0159                   /* ImageSShortThe number of units that span the height of the image, in terms of integer ClipPath coordinates. */                  
#define Exif.Image.Indexed 0x015a                          /* ImageShortIndexed images are images where the 'pixels' do not represent color values, but rather an index (usually 8-bit) into a separate color table, the ColorMap. */           
#define Exif.Image.JPEGTables 0x015b                       /* ImageUndefinedThis optional tag may be used to encode the JPEG quantization andHuffman tables for subsequent use by the JPEG decompression process. */              
#define Exif.Image.OPIProxy 0x015f                         /* ImageShortOPIProxy gives information concerning whether this image is a low-resolution proxy of a high-resolution image (Adobe OPI). */                                                 
#define Exif.Image.JPEGProc 0x0200                         /* ImageLongThis field indicates the process used to produce the compressed data */            
#define Exif.Image.JPEGInterchangeFormat 0x0201            /* ImageLongThe offset to the start byte (SOI) of JPEG compressed thumbnail data. This is not used for primary image JPEG data. */                                                              
#define Exif.Image.JPEGInterchangeFormatLength 0x0202      /* ImageLongThe number of bytes of JPEG compressed thumbnail data. This is not used for primary image JPEG data. JPEG thumbnails are not divided but are recorded as a continuous JPEG bitstream from SOI to EOI. Appn and COM markers should not be recorded. Compressed thumbnails must be recorded in no more than 64 Kbytes, including all other data to be recorded in APP1. */                               
#define Exif.Image.JPEGRestartInterval 0x0203              /* ImageShortThis Field indicates the length of the restart interval used in the compressed image data. */                       
#define Exif.Image.JPEGLosslessPredictors 0x0205           /* ImageShortThis Field points to a list of lossless predictor-selection values, one per component. */                          
#define Exif.Image.JPEGPointTransforms 0x0206              /* ImageShortThis Field points to a list of point transform values, one per component. */                       
#define Exif.Image.JPEGQTables 0x0207                      /* ImageLongThis Field points to a list of offsets to the quantization tables, one per component. */               
#define Exif.Image.JPEGDCTables 0x0208                     /* ImageLongThis Field points to a list of offsets to the DC Huffman tables or the lossless Huffman tables, one per component. */                                                     
#define Exif.Image.JPEGACTables 0x0209                     /* ImageLongThis Field points to a list of offsets to the Huffman AC tables, one per component. */                
#define Exif.Image.YCbCrCoefficients 0x0211                /* ImageRationalThe matrix coefficients for transformation from RGB to YCbCr image data. No default is given in TIFF; but here the value given in Appendix E, "Color Space Guidelines", is used as the default. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability this condition. */                     
#define Exif.Image.YCbCrSubSampling 0x0212                 /* ImageShortThe sampling ratio of chrominance components in relation to the luminance component. In JPEG compressed data a JPEG marker is used instead of this tag. */                    
#define Exif.Image.YCbCrPositioning 0x0213                 /* ImageShortThe position of chrominance components in relation to the luminance component. This field is designated only for JPEG compressed data or uncompressed YCbCr data. The TIFF default is 1 (centered); but when Y:Cb:Cr = 4:2:2 it is recommended in this standard that 2 (co-sited) be used to record data, in order to improve the image quality when viewed on TV systems. When this field does not exist, the reader shall assume the TIFF default. In the case of Y:Cb:Cr = 4:2:0, the TIFF default (centered) is recommended. If the reader does not have the capability of supporting both kinds of <YCbCrPositioning>, it shall follow the TIFF default regardless of the value in this field. It is preferable that readers be able to support both centered and co-sited positioning. */                    
#define Exif.Image.ReferenceBlackWhite 0x0214              /* ImageRationalThe reference black point value and reference white point value. No defaults are given in TIFF, but the values below are given as defaults here. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability these conditions. */                       
#define Exif.Image.XMLPacket 0x02bc                        /* ImageByteXMP Metadata (Adobe technote 9-14-02) */             
#define Exif.Iop.RelatedImageFileFormat 0x1000             /* IopAsciiFile format of image file */                        
#define Exif.Iop.RelatedImageWidth 0x1001                  /* IopLongImage width */                   
#define Exif.Iop.RelatedImageLength 0x1002                 /* IopLongImage height */                    
#define Exif.Image.Rating 0x4746                           /* ImageShortRating tag used by Windows */          
#define Exif.Image.RatingPercent 0x4749                    /* ImageShortRating tag used by Windows, value in percent */                 
#define Exif.Image.ImageID 0x800d                          /* ImageAsciiImageID is the full pathname of the original, high-resolution image, or any other identifying string that uniquely identifies the original image (Adobe OPI). */           
#define Exif.Image.CFARepeatPatternDim 0x828d              /* ImageShortContains two values representing the minimum rows and columns to define the repeating patterns of the color filter array */                                                            
#define Exif.Image.CFAPattern 0x828e                       /* ImageByteIndicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used. It does not apply to all sensing methods */              
#define Exif.Image.BatteryLevel 0x828f                     /* ImageRationalContains a value of the battery level as a fraction or string */                
#define Exif.Image.Copyright 0x8298                        /* ImageAsciiCopyright information. In this standard the tag is used to indicate both the photographer and editor copyrights. It is the copyright notice of the person or organization claiming rights to the image. The Interoperability copyright statement including date and rights should be written in this field; e.g., "Copyright, John Smith, 19xx. All rights reserved.". In this standard the field records both the photographer and editor copyrights, with each recorded in a separate part of the statement. When there is a clear distinction between the photographer and editor copyrights, these are to be written in the order of photographer followed by editor copyright, separated by NULL (in this case since the statement also ends with a NULL, there are two NULL codes). When only the photographer copyright is given, it is terminated by one NULL code . When only the editor copyright is given, the photographer copyright part consists of one space followed by a terminating NULL code, then the editor copyright is given. When the field is left blank, it is treated as unknown. */             
#define Exif.Photo.ExposureTime 0x829a                     /* PhotoRationalExposure time, given in seconds (sec). */                
#define Exif.Image.ExposureTime 0x829a                     /* ImageRationalExposure time, given in seconds. */                
#define Exif.Photo.FNumber 0x829d                          /* PhotoRationalThe F number. */           
#define Exif.Image.FNumber 0x829d                          /* ImageRationalThe F number. */           
#define Exif.Image.IPTCNAA 0x83bb                          /* ImageLongContains an IPTC/NAA record */           
#define Exif.Image.ImageResources 0x8649                   /* ImageByteContains information embedded by the Adobe Photoshop application */                  
#define Exif.Image.ExifTag 0x8769                          /* ImageLongA pointer to the Exif IFD. Interoperability, Exif IFD has the same structure as that of the IFD specified in TIFF. ordinarily, however, it does not contain image data as in the case of TIFF. */           
#define Exif.Image.InterColorProfile 0x8773                /* ImageUndefinedContains an InterColor Consortium (ICC) format color space characterization/profile */                     
#define Exif.Photo.ExposureProgram 0x8822                  /* PhotoShortThe class of the program used by the camera to set exposure when the picture is taken. */                   
#define Exif.Image.ExposureProgram 0x8822                  /* ImageShortThe class of the program used by the camera to set exposure when the picture is taken. */                   
#define Exif.Photo.SpectralSensitivity 0x8824              /* PhotoAsciiIndicates the spectral sensitivity of each channel of the camera used. The tag value is an ASCII string compatible with the standard developed by the ASTM Technical Committee. */                       
#define Exif.Image.SpectralSensitivity 0x8824              /* ImageAsciiIndicates the spectral sensitivity of each channel of the camera used. */                       
#define Exif.Image.GPSTag 0x8825                           /* ImageLongA pointer to the GPS Info IFD. The Interoperability structure of the GPS Info IFD, like that of Exif IFD, has no image data. */                                               
#define Exif.Image.ISOSpeedRatings 0x8827                  /* ImageShortIndicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232. */                   
#define Exif.Photo.ISOSpeedRatings 0x8827                  /* PhotoShortIndicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232. */                   
#define Exif.Photo.OECF 0x8828                             /* PhotoUndefinedIndicates the Opto-Electoric Conversion Function (OECF) specified in ISO 14524. <OECF> is the relationship between the camera optical input and the image values. */        
#define Exif.Image.OECF 0x8828                             /* ImageUndefinedIndicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524. */        
#define Exif.Image.Interlace 0x8829                        /* ImageShortIndicates the field number of multifield images. */             
#define Exif.Image.TimeZoneOffset 0x882a                   /* ImageSShortThis optional tag encodes the time zone of the camera clock (relativeto Greenwich Mean Time) used to create the DataTimeOriginal tag-valuewhen the picture was taken. It may also contain the time zone offsetof the clock used to create the DateTime tag-value when the image wasmodified. */                  
#define Exif.Image.SelfTimerMode 0x882b                    /* ImageShortNumber of seconds image capture was delayed from button press. */                 
#define Exif.Photo.SensitivityType 0x8830                  /* PhotoShortThe SensitivityType tag indicates PhotographicSensitivity tag. which one of the parameters of ISO12232 is the Although it is an optional tag, it should be recorded when a PhotographicSensitivity tag is recorded. Value = 4, 5, 6, or 7 may be used in case that the values of plural parameters are the same. */                                                        
#define Exif.Photo.StandardOutputSensitivity 0x8831        /* PhotoLongThis tag indicates the standard output sensitivity value of a camera or input device defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded. */                             
#define Exif.Photo.RecommendedExposureIndex 0x8832         /* PhotoLongThis tag indicates the recommended exposure index value of a camera or input device defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded. */                            
#define Exif.Photo.ISOSpeed 0x8833                         /* PhotoLongThis tag indicates the ISO speed value of a camera or input device that is defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded. */            
#define Exif.Photo.ISOSpeedLatitudeyyy 0x8834              /* PhotoLongThis tag indicates the ISO speed latitude yyy value of a camera or input device that is defined in ISO 12232. However, this tag shall not be recorded without ISOSpeed and ISOSpeedLatitudezzz. */                       
#define Exif.Photo.ISOSpeedLatitudezzz 0x8835              /* PhotoLongThis tag indicates the ISO speed latitude zzz value of a camera or input device that is defined in ISO 12232. However, this tag shall not be recorded without ISOSpeed and ISOSpeedLatitudeyyy. */                       
#define Exif.Photo.ExifVersion 0x9000                      /* PhotoUndefinedThe version of this standard supported. Nonexistence of this field is taken to mean nonconformance to the standard. */                                                    
#define Exif.Photo.DateTimeOriginal 0x9003                 /* PhotoAsciiThe date and time when the original image data was generated. For a digital still camera the date and time the picture was taken are recorded. */                    
#define Exif.Image.DateTimeOriginal 0x9003                 /* ImageAsciiThe date and time when the original image data was generated. */                    
#define Exif.Photo.DateTimeDigitized 0x9004                /* PhotoAsciiThe date and time when the image was stored as digital data. */                     
#define Exif.Photo.ComponentsConfiguration 0x9101          /* PhotoUndefinedInformation specific to compressed data. The channels of each component are arranged in order from the 1st component to the 4th. For uncompressed data the data arrangement is given in the <PhotometricInterpretation> tag. However, since <PhotometricInterpretation> can only express the order of Y, Cb and Cr, this tag is provided for cases when compressed data uses components other than Y, Cb, and Cr and to enable support of other sequences. */                           
#define Exif.Image.CompressedBitsPerPixel 0x9102           /* ImageRationalSpecific to compressed data; states the compressed bits per pixel. */                          
#define Exif.Photo.CompressedBitsPerPixel 0x9102           /* PhotoRationalInformation specific to compressed data. The compression mode used for a compressed image is indicated in unit bits per pixel. */                          
#define Exif.Image.ShutterSpeedValue 0x9201                /* ImageSRationalShutter speed. */                     
#define Exif.Photo.ShutterSpeedValue 0x9201                /* PhotoSRationalShutter speed. The unit is the APEX (Additive System of Photographic Exposure) setting. */                     
#define Exif.Photo.ApertureValue 0x9202                    /* PhotoRationalThe lens aperture. The unit is the APEX value. */                 
#define Exif.Image.ApertureValue 0x9202                    /* ImageRationalThe lens aperture. */                 
#define Exif.Image.BrightnessValue 0x9203                  /* ImageSRationalThe value of brightness. */                   
#define Exif.Photo.BrightnessValue 0x9203                  /* PhotoSRationalThe value of brightness. The unit is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99. */                                                        
#define Exif.Photo.ExposureBiasValue 0x9204                /* PhotoSRationalThe exposure bias. The units is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99. */                                                          
#define Exif.Image.ExposureBiasValue 0x9204                /* ImageSRationalThe exposure bias. */                     
#define Exif.Photo.MaxApertureValue 0x9205                 /* PhotoRationalThe smallest F number of the lens. The unit is the APEX value. Ordinarily it is given in the range of 00.00 to 99.99, but it is not limited to this range. */                    
#define Exif.Image.MaxApertureValue 0x9205                 /* ImageRationalThe smallest F number of the lens. */                    
#define Exif.Image.SubjectDistance 0x9206                  /* ImageSRationalThe distance to the subject, given in meters. */                   
#define Exif.Photo.SubjectDistance 0x9206                  /* PhotoRationalThe distance to the subject, given in meters. */                   
#define Exif.Photo.MeteringMode 0x9207                     /* PhotoShortThe metering mode. */                
#define Exif.Image.MeteringMode 0x9207                     /* ImageShortThe metering mode. */                
#define Exif.Image.LightSource 0x9208                      /* ImageShortThe kind of light source. */               
#define Exif.Photo.LightSource 0x9208                      /* PhotoShortThe kind of light source. */               
#define Exif.Photo.Flash 0x9209                            /* PhotoShortThis tag is recorded when an image is taken using a strobe light (flash). */         
#define Exif.Image.Flash 0x9209                            /* ImageShortIndicates the status of flash when the image was shot. */         
#define Exif.Image.FocalLength 0x920a                      /* ImageRationalThe actual focal length of the lens, in mm. */               
#define Exif.Photo.FocalLength 0x920a                      /* PhotoRationalThe actual focal length of the lens, in mm. Conversion is not made to the focal length of a 35 mm film camera. */                                                    
#define Exif.Image.FlashEnergy 0x920b                      /* ImageRationalAmount of flash energy (BCPS). */               
#define Exif.Image.SpatialFrequencyResponse 0x920c         /* ImageUndefinedSFR of the camera. */                            
#define Exif.Image.Noise 0x920d                            /* ImageUndefinedNoise measurement values. */         
#define Exif.Image.FocalPlaneXResolution 0x920e            /* ImageRationalNumber of pixels per FocalPlaneResolutionUnit (37392) in ImageWidth direction for main image. */                         
#define Exif.Image.FocalPlaneYResolution 0x920f            /* ImageRationalNumber of pixels per FocalPlaneResolutionUnit (37392) in ImageLength direction for main image. */                         
#define Exif.Image.FocalPlaneResolutionUnit 0x9210         /* ImageShortUnit of measurement for FocalPlaneXResolution(37390) and FocalPlaneYResolution(37391). */                            
#define Exif.Image.ImageNumber 0x9211                      /* ImageLongNumber assigned to an image, e.g., in a chained image burst. */               
#define Exif.Image.SecurityClassification 0x9212           /* ImageAsciiSecurity classification assigned to the image. */                          
#define Exif.Image.ImageHistory 0x9213                     /* ImageAsciiRecord of what has been done to the image. */                
#define Exif.Image.SubjectLocation 0x9214                  /* ImageShortIndicates the location and area of the main subject in the overall scene. */                   
#define Exif.Photo.SubjectArea 0x9214                      /* PhotoShortThis tag indicates the location and area of the main subject in the overall scene. */               
#define Exif.Image.ExposureIndex 0x9215                    /* ImageRationalEncodes the camera exposure index setting when image was captured. */                 
#define Exif.Image.TIFFEPStandardID 0x9216                 /* ImageByteContains four ASCII characters representing the TIFF/EP standard version of a TIFF/EP file, eg '1', '0', '0', '0' */                                                         
#define Exif.Image.SensingMethod 0x9217                    /* ImageShortType of image sensor. */                 
#define Exif.Photo.MakerNote 0x927c                        /* PhotoUndefinedA tag for manufacturers of Exif writers to record any desired information. The contents are up to the manufacturer. */                                                  
#define Exif.Photo.UserComment 0x9286                      /* PhotoCommentA tag for Exif users to write keywords or comments on the image besides those in <ImageDescription>, and without the character code limitations of the <ImageDescription> tag. */               
#define Exif.Photo.SubSecTime 0x9290                       /* PhotoAsciiA tag used to record fractions of seconds for the <DateTime> tag. */              
#define Exif.Photo.SubSecTimeOriginal 0x9291               /* PhotoAsciiA tag used to record fractions of seconds for the <DateTimeOriginal> tag. */                      
#define Exif.Photo.SubSecTimeDigitized 0x9292              /* PhotoAsciiA tag used to record fractions of seconds for the <DateTimeDigitized> tag. */                       
#define Exif.Image.XPTitle 0x9c9b                          /* ImageByteTitle tag used by Windows, encoded in UCS2 */           
#define Exif.Image.XPComment 0x9c9c                        /* ImageByteComment tag used by Windows, encoded in UCS2 */             
#define Exif.Image.XPAuthor 0x9c9d                         /* ImageByteAuthor tag used by Windows, encoded in UCS2 */            
#define Exif.Image.XPKeywords 0x9c9e                       /* ImageByteKeywords tag used by Windows, encoded in UCS2 */              
#define Exif.Image.XPSubject 0x9c9f                        /* ImageByteSubject tag used by Windows, encoded in UCS2 */             
#define Exif.Photo.FlashpixVersion 0xa000                  /* PhotoUndefinedThe FlashPix format version supported by a FPXR file. */                   
#define Exif.Photo.ColorSpace 0xa001                       /* PhotoShortThe color space information tag is always recorded as the color space specifier. Normally sRGB is used to define the color space based on the PC monitor conditions and environment. If a color space other than sRGB is used, Uncalibrated is set. Image data recorded as Uncalibrated can be treated as sRGB when it is converted to FlashPix. */              
#define Exif.Photo.PixelXDimension 0xa002                  /* PhotoLongInformation specific to compressed data. When a compressed file is recorded, the valid width of the meaningful image must be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file. */                   
#define Exif.Photo.PixelYDimension 0xa003                  /* PhotoLongInformation specific to compressed data. When a compressed file is recorded, the valid height of the meaningful image must be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file. Since data padding is unnecessary in the vertical direction, the number of lines recorded in this valid image height tag will in fact be the same as that recorded in the SOF. */                   
#define Exif.Photo.RelatedSoundFile 0xa004                 /* PhotoAsciiThis tag is used to record the name of an audio file related to the image data. The only relational information recorded here is the Exif audio file name and extension (an ASCII string consisting of 8 characters + '.' + 3 characters). The path is not recorded. */                    
#define Exif.Photo.InteroperabilityTag 0xa005              /* PhotoLongInteroperability IFD is composed of tags which stores the information to ensure the Interoperability and pointed by the following tag located in Exif IFD. The Interoperability structure of Interoperability IFD is the same as TIFF defined IFD structure but does not contain the image data characteristically compared with normal TIFF IFD. */                       
#define Exif.Photo.FlashEnergy 0xa20b                      /* PhotoRationalIndicates the strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds (BCPS). */                                                    
#define Exif.Photo.SpatialFrequencyResponse 0xa20c         /* PhotoUndefinedThis tag records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233. */                            
#define Exif.Photo.FocalPlaneXResolution 0xa20e            /* PhotoRationalIndicates the number of pixels in the image width (X) direction per <FocalPlaneResolutionUnit> on the camera focal plane. */                                                              
#define Exif.Photo.FocalPlaneYResolution 0xa20f            /* PhotoRationalIndicates the number of pixels in the image height (V) direction per <FocalPlaneResolutionUnit> on the camera focal plane. */                                                              
#define Exif.Photo.FocalPlaneResolutionUnit 0xa210         /* PhotoShortIndicates the unit for measuring <FocalPlaneXResolution> and <FocalPlaneYResolution>. This value is the same as the <ResolutionUnit>. */                            
#define Exif.Photo.SubjectLocation 0xa214                  /* PhotoShortIndicates the location of the main subject in the scene. The value of this tag represents the pixel at the center of the main subject relative to the left edge, prior to rotation processing as per the <Rotation> tag. The first value indicates the X column number and second indicates the Y row number. */                                                        
#define Exif.Photo.ExposureIndex 0xa215                    /* PhotoRationalIndicates the exposure index selected on the camera or input device at the time the image is captured. */                 
#define Exif.Photo.SensingMethod 0xa217                    /* PhotoShortIndicates the image sensor type on the camera or input device. */                 
#define Exif.Photo.FileSource 0xa300                       /* PhotoUndefinedIndicates the image source. If a DSC recorded the image, this tag value of this tag always be set to 3, indicating that the image was recorded on a DSC. */              
#define Exif.Photo.SceneType 0xa301                        /* PhotoUndefinedIndicates the type of scene. If a DSC recorded the image, this tag value must always be set to 1, indicating that the image was directly photographed. */             
#define Exif.Photo.CFAPattern 0xa302                       /* PhotoUndefinedIndicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used. It does not apply to all sensing methods. */              
#define Exif.Photo.CustomRendered 0xa401                   /* PhotoShortThis tag indicates the use of special processing on image data, such as rendering geared to output. When special processing is performed, the reader is expected to disable or minimize any further processing. */                  
#define Exif.Photo.ExposureMode 0xa402                     /* PhotoShortThis tag indicates the exposure mode set when the image was shot. In auto-bracketing mode, the camera shoots a series of frames of the same scene at different exposure settings. */                
#define Exif.Photo.WhiteBalance 0xa403                     /* PhotoShortThis tag indicates the white balance mode set when the image was shot. */                
#define Exif.Photo.DigitalZoomRatio 0xa404                 /* PhotoRationalThis tag indicates the digital zoom ratio when the image was shot. If the numerator of the recorded value is 0, this indicates that digital zoom was not used. */                    
#define Exif.Photo.FocalLengthIn35mmFilm 0xa405            /* PhotoShortThis tag indicates the equivalent focal length assuming a 35mm film camera, in mm. A value of 0 means the focal length is unknown. Note that this tag differs from the <FocalLength> tag. */                         
#define Exif.Photo.SceneCaptureType 0xa406                 /* PhotoShortThis tag indicates the type of scene that was shot. It can also be used to record the mode in which the image was shot. Note that this differs from the <SceneType> tag. */                    
#define Exif.Photo.GainControl 0xa407                      /* PhotoShortThis tag indicates the degree of overall image gain adjustment. */               
#define Exif.Photo.Contrast 0xa408                         /* PhotoShortThis tag indicates the direction of contrast processing applied by the camera when the image was shot. */            
#define Exif.Photo.Saturation 0xa409                       /* PhotoShortThis tag indicates the direction of saturation processing applied by the camera when the image was shot. */              
#define Exif.Photo.Sharpness 0xa40a                        /* PhotoShortThis tag indicates the direction of sharpness processing applied by the camera when the image was shot. */             
#define Exif.Photo.DeviceSettingDescription 0xa40b         /* PhotoUndefinedThis tag indicates information on the picture-taking conditions of a particular camera model. The tag is used only to indicate the picture-taking conditions in the reader. */                            
#define Exif.Photo.SubjectDistanceRange 0xa40c             /* PhotoShortThis tag indicates the distance to the subject. */                        
#define Exif.Photo.ImageUniqueID 0xa420                    /* PhotoAsciiThis tag indicates an identifier assigned uniquely to each image. It is recorded as an ASCII string equivalent to hexadecimal notation and 128-bit fixed length. */                 
#define Exif.Photo.CameraOwnerName 0xa430                  /* PhotoAsciiThis tag records the owner of a camera used in photography as an ASCII string. */                   
#define Exif.Photo.BodySerialNumber 0xa431                 /* PhotoAsciiThis tag records the serial number of the body of the camera that was used in photography as an ASCII string. */                                                         
#define Exif.Photo.LensSpecification 0xa432                /* PhotoRationalThis tag notes minimum focal length, maximum focal length, minimum F number in the minimum focal length, and minimum F number in the maximum focal length, which are specification information for the lens that was used in photography. When the minimum F number is unknown, the notation is 0/0 */                     
#define Exif.Photo.LensMake 0xa433                         /* PhotoAsciiThis tag records the lens manufactor as an ASCII string. */            
#define Exif.Photo.LensModel 0xa434                        /* PhotoAsciiThis tag records the lens's model name and model number as an ASCII string. */             
#define Exif.Photo.LensSerialNumber 0xa435                 /* PhotoAsciiThis tag records the serial number of the interchangeable lens that was used in photography as an ASCII string. */                                                         
#define Exif.Image.PrintImageMatching 0xc4a5               /* ImageUndefinedPrint Image Matching, description needed. */                      
#define Exif.Image.DNGVersion 0xc612                       /* ImageByteThis tag encodes the DNG four-tier version number. For files compliant with version 1.1.0.0 of the DNG specification, this tag should contain the bytes: 1, 1, 0, 0. */              
#define Exif.Image.DNGBackwardVersion 0xc613               /* ImageByteThis tag specifies the oldest version of the Digital Negative specification for which a file is compatible. Readers shouldnot attempt to read a file if this tag specifies a version number that is higher than the version number of the specification the reader was based on. In addition to checking the version tags, readers should, for all tags, check the types, counts, and values, to verify it is able to correctly read the file. */                      
#define Exif.Image.UniqueCameraModel 0xc614                /* ImageAsciiDefines a unique, non-localized name for the camera model that created the image in the raw file. This name should include the manufacturer's name to avoid conflicts, and should not be localized, even if the camera name itself is localized for different markets (see LocalizedCameraModel). This string may be used by reader software to index into per-model preferences and replacement profiles. */                     
#define Exif.Image.LocalizedCameraModel 0xc615             /* ImageByteSimilar to the UniqueCameraModel field, except the name can be localized for different markets to match the localization of the camera name. */                        
#define Exif.Image.CFAPlaneColor 0xc616                    /* ImageByteProvides a mapping between the values in the CFAPattern tag and the plane numbers in LinearRaw space. This is a required tag for non-RGB CFA images. */                 
#define Exif.Image.CFALayout 0xc617                        /* ImageShortDescribes the spatial layout of the CFA. */             
#define Exif.Image.LinearizationTable 0xc618               /* ImageShortDescribes a lookup table that maps stored values into linear values. This tag is typically used to increase compression ratios by storing the raw data in a non-linear, more visually uniform space with fewer total encoding levels. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel. */                      
#define Exif.Image.BlackLevelRepeatDim 0xc619              /* ImageShortSpecifies repeat pattern size for the BlackLevel tag. */                       
#define Exif.Image.BlackLevel 0xc61a                       /* ImageRationalSpecifies the zero light (a.k.a. thermal black or black current) encoding level, as a repeating pattern. The origin of this pattern is the top-left corner of the ActiveArea rectangle. The values are stored in row-column-sample scan order. */              
#define Exif.Image.BlackLevelDeltaH 0xc61b                 /* ImageSRationalIf the zero light encoding level is a function of the image column, BlackLevelDeltaH specifies the difference between the zero light encoding level for each column and the baseline zero light encoding level. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel. */                                                         
#define Exif.Image.BlackLevelDeltaV 0xc61c                 /* ImageSRationalIf the zero light encoding level is a function of the image row, this tag specifies the difference between the zero light encoding level for each row and the baseline zero light encoding level. If SamplesPerPixel is not equal to one, this single table applies to all the samples for each pixel. */                    
#define Exif.Image.WhiteLevel 0xc61d                       /* ImageShortThis tag specifies the fully saturated encoding level for the raw sample values. Saturation is caused either by the sensor itself becoming highly non-linear in response, or by the camera's analog to digital converter clipping. */              
#define Exif.Image.DefaultScale 0xc61e                     /* ImageRationalDefaultScale is required for cameras with non-square pixels. It specifies the default scale factors for each direction to convert the image to square pixels. Typically these factors are selected to approximately preserve total pixel count. For CFA images that use CFALayout equal to 2, 3, 4, or 5, such as the Fujifilm SuperCCD, these two values should usually differ by a factor of 2.0. */                
#define Exif.Image.DefaultCropOrigin 0xc61f                /* ImageShortRaw images often store extra pixels around the edges of the final image. These extra pixels help prevent interpolation artifacts near the edges of the final image. DefaultCropOrigin specifies the origin of the final image area, in raw image coordinates (i.e., before the DefaultScale has been applied), relative to the top-left corner of the ActiveArea rectangle. */                     
#define Exif.Image.DefaultCropSize 0xc620                  /* ImageShortRaw images often store extra pixels around the edges of the final image. These extra pixels help prevent interpolation artifacts near the edges of the final image. DefaultCropSize specifies the size of the final image area, in raw image coordinates (i.e., before the DefaultScale has been applied). */                   
#define Exif.Image.ColorMatrix1 0xc621                     /* ImageSRationalColorMatrix1 defines a transformation matrix that converts XYZ values to reference camera native color space values, under the first calibration illuminant. The matrix values are stored in row scan order. The ColorMatrix1 tag is required for all non-monochrome DNG files. */                
#define Exif.Image.ColorMatrix2 0xc622                     /* ImageSRationalColorMatrix2 defines a transformation matrix that converts XYZ values to reference camera native color space values, under the second calibration illuminant. The matrix values are stored in row scan order. */                
#define Exif.Image.CameraCalibration1 0xc623               /* ImageSRationalCameraClalibration1 defines a calibration matrix that transforms reference camera native space values to individual camera native space values under the first calibration illuminant. The matrix is stored in row scan order. This matrix is stored separately from the matrix specified by the ColorMatrix1 tag to allow raw converters to swap in replacement color matrices based on UniqueCameraModel tag, while still taking advantage of any per-individual camera calibration performed by the camera manufacturer. */                      
#define Exif.Image.CameraCalibration2 0xc624               /* ImageSRationalCameraCalibration2 defines a calibration matrix that transforms reference camera native space values to individual camera native space values under the second calibration illuminant. The matrix is stored in row scan order. This matrix is stored separately from the matrix specified by the ColorMatrix2 tag to allow raw converters to swap in replacement color matrices based on UniqueCameraModel tag, while still taking advantage of any per-individual camera calibration performed by the camera manufacturer. */                      
#define Exif.Image.ReductionMatrix1 0xc625                 /* ImageSRationalReductionMatrix1 defines a dimensionality reduction matrix for use as the first stage in converting color camera native space values to XYZ values, under the first calibration illuminant. This tag may only be used if ColorPlanes is greater than 3. The matrix is stored in row scan order. */                    
#define Exif.Image.ReductionMatrix2 0xc626                 /* ImageSRationalReductionMatrix2 defines a dimensionality reduction matrix for use as the first stage in converting color camera native space values to XYZ values, under the second calibration illuminant. This tag may only be used if ColorPlanes is greater than 3. The matrix is stored in row scan order. */                    
#define Exif.Image.AnalogBalance 0xc627                    /* ImageRationalNormally the stored raw values are not white balanced, since any digital white balancing will reduce the dynamic range of the final image if the user decides to later adjust the white balance; however, if camera hardware is capable of white balancing the color channels before the signal is digitized, it can improve the dynamic range of the final image. AnalogBalance defines the gain, either analog (recommended) or digital (not recommended) that has been applied the stored raw values. */                 
#define Exif.Image.AsShotNeutral 0xc628                    /* ImageShortSpecifies the selected white balance at time of capture, encoded as the coordinates of a perfectly neutral color in linear reference space values. The inclusion of this tag precludes the inclusion of the AsShotWhiteXY tag. */                 
#define Exif.Image.AsShotWhiteXY 0xc629                    /* ImageRationalSpecifies the selected white balance at time of capture, encoded as x-y chromaticity coordinates. The inclusion of this tag precludes the inclusion of the AsShotNeutral tag. */                 
#define Exif.Image.BaselineExposure 0xc62a                 /* ImageSRationalCamera models vary in the trade-off they make between highlight headroom and shadow noise. Some leave a significant amount of highlight headroom during a normal exposure. This allows significant negative exposure compensation to be applied during raw conversion, but also means normal exposures will contain more shadow noise. Other models leave less headroom during normal exposures. This allows for less negative exposure compensation, but results in lower shadow noise for normal exposures. Because of these differences, a raw converter needs to vary the zero point of its exposure compensation control from model to model. BaselineExposure specifies by how much (in EV units) to move the zero point. Positive values result in brighter default results, while negative values result in darker default results. */                    
#define Exif.Image.BaselineNoise 0xc62b                    /* ImageRationalSpecifies the relative noise level of the camera model at a baseline ISO value of 100, compared to a reference camera model. Since noise levels tend to vary approximately with the square root of the ISO value, a raw converter can use this value, combined with the current ISO, to estimate the relative noise level of the current image. */                 
#define Exif.Image.BaselineSharpness 0xc62c                /* ImageRationalSpecifies the relative amount of sharpening required for this camera model, compared to a reference camera model. Camera models vary in the strengths of their anti-aliasing filters. Cameras with weak or no filters require less sharpening than cameras with strong anti-aliasing filters. */                     
#define Exif.Image.BayerGreenSplit 0xc62d                  /* ImageLongOnly applies to CFA images using a Bayer pattern filter array. This tag specifies, in arbitrary units, how closely the values of the green pixels in the blue/green rows track the values of the green pixels in the red/green rows. A value of zero means the two kinds of green pixels track closely, while a non-zero value means they sometimes diverge. The useful range for this tag is from 0 (no divergence) to about 5000 (quite large divergence). */                   
#define Exif.Image.LinearResponseLimit 0xc62e              /* ImageRationalSome sensors have an unpredictable non-linearity in their response as they near the upper limit of their encoding range. This non-linearity results in color shifts in the highlight areas of the resulting image unless the raw converter compensates for this effect. LinearResponseLimit specifies the fraction of the encoding range above which the response may become significantly non-linear. */                       
#define Exif.Image.CameraSerialNumber 0xc62f               /* ImageAsciiCameraSerialNumber contains the serial number of the camera or camera body that captured the image. */                      
#define Exif.Image.LensInfo 0xc630                         /* ImageRationalContains information about the lens that captured the image. If the minimum f-stops are unknown, they should be encoded as 0/0. */            
#define Exif.Image.ChromaBlurRadius 0xc631                 /* ImageRationalChromaBlurRadius provides a hint to the DNG reader about how much chroma blur should be applied to the image. If this tag is omitted, the reader will use its default amount of chroma blurring. Normally this tag is only included for non-CFA images, since the amount of chroma blur required for mosaic images is highly dependent on the de-mosaic algorithm, in which case the DNG reader's default value is likely optimized for its particular de-mosaic algorithm. */                    
#define Exif.Image.AntiAliasStrength 0xc632                /* ImageRationalProvides a hint to the DNG reader about how strong the camera's anti-alias filter is. A value of 0.0 means no anti-alias filter (i.e., the camera is prone to aliasing artifacts with some subjects), while a value of 1.0 means a strong anti-alias filter (i.e., the camera almost never has aliasing artifacts). */                                                          
#define Exif.Image.ShadowScale 0xc633                      /* ImageSRationalThis tag is used by Adobe Camera Raw to control the sensitivity of its 'Shadows' slider. */               
#define Exif.Image.DNGPrivateData 0xc634                   /* ImageByteProvides a way for camera manufacturers to store private data in the DNG file for use by their own raw converters, and to have that data preserved by programs that edit DNG files. */                  
#define Exif.Image.MakerNoteSafety 0xc635                  /* ImageShortMakerNoteSafety lets the DNG reader know whether the EXIF MakerNote tag is safe to preserve along with the rest of the EXIF data. File browsers and other image management software processing an image with a preserved MakerNote should be aware that any thumbnail image embedded in the MakerNote may be stale, and may not reflect the current state of the full size image. */                   
#define Exif.Image.CalibrationIlluminant1 0xc65a           /* ImageShortThe illuminant used for the first set of color calibration tags (ColorMatrix1, CameraCalibration1, ReductionMatrix1). The legal values for this tag are the same as the legal values for the LightSource EXIF tag. */                          
#define Exif.Image.CalibrationIlluminant2 0xc65b           /* ImageShortThe illuminant used for an optional second set of color calibration tags (ColorMatrix2, CameraCalibration2, ReductionMatrix2). The legal values for this tag are the same as the legal values for the CalibrationIlluminant1 tag; however, if both are included, neither is allowed to have a value of 0 (unknown). */                                                               
#define Exif.Image.BestQualityScale 0xc65c                 /* ImageRationalFor some cameras, the best possible image quality is not achieved by preserving the total pixel count during conversion. For example, Fujifilm SuperCCD images have maximum detail when their total pixel count is doubled. This tag specifies the amount by which the values of the DefaultScale tag need to be multiplied to achieve the best quality image size. */                    
#define Exif.Image.RawDataUniqueID 0xc65d                  /* ImageByteThis tag contains a 16-byte unique identifier for the raw image data in the DNG file. DNG readers can use this tag to recognize a particular raw image, even if the file's name or the metadata contained in the file has been changed. If a DNG writer creates such an identifier, it should do so using an algorithm that will ensure that it is very unlikely two different images will end up having the same identifier. */                   
#define Exif.Image.OriginalRawFileName 0xc68b              /* ImageByteIf the DNG file was converted from a non-DNG raw file, then this tag contains the file name of that original raw file. */                                                            
#define Exif.Image.OriginalRawFileData 0xc68c              /* ImageUndefinedIf the DNG file was converted from a non-DNG raw file, then this tag contains the compressed contents of that original raw file. The contents of this tag always use the big-endian byte order. The tag contains a sequence of data blocks. Future versions of the DNG specification may define additional data blocks, so DNG readers should ignore extra bytes when parsing this tag. DNG readers should also detect the case where data blocks are missing from the end of the sequence, and should assume a default value for all the missing blocks. There are no padding or alignment bytes between data blocks. */                       
#define Exif.Image.ActiveArea 0xc68d                       /* ImageShortThis rectangle defines the active (non-masked) pixels of the sensor. The order of the rectangle coordinates is: top, left, bottom, right. */              
#define Exif.Image.MaskedAreas 0xc68e                      /* ImageShortThis tag contains a list of non-overlapping rectangle coordinates of fully masked pixels, which can be optionally used by DNG readers to measure the black encoding level. The order of each rectangle's coordinates is: top, left, bottom, right. If the raw image data has already had its black encoding level subtracted, then this tag should not be used, since the masked pixels are no longer useful. */               
#define Exif.Image.AsShotICCProfile 0xc68f                 /* ImageUndefinedThis tag contains an ICC profile that, in conjunction with the AsShotPreProfileMatrix tag, provides the camera manufacturer with a way to specify a default color rendering from camera color space coordinates (linear reference values) into the ICC profile connection space. The ICC profile connection space is an output referred colorimetric space, whereas the other color calibration tags in DNG specify a conversion into a scene referred colorimetric space. This means that the rendering in this profile should include any desired tone and gamut mapping needed to convert between scene referred values and output referred values. */                    
#define Exif.Image.AsShotPreProfileMatrix 0xc690           /* ImageSRationalThis tag is used in conjunction with the AsShotICCProfile tag. It specifies a matrix that should be applied to the camera color space coordinates before processing the values through the ICC profile specified in the AsShotICCProfile tag. The matrix is stored in the row scan order. If ColorPlanes is greater than three, then this matrix can (but is not required to) reduce the dimensionality of the color data down to three components, in which case the AsShotICCProfile should have three rather than ColorPlanes input components. */                          
#define Exif.Image.CurrentICCProfile 0xc691                /* ImageUndefinedThis tag is used in conjunction with the CurrentPreProfileMatrix tag. The CurrentICCProfile and CurrentPreProfileMatrix tags have the same purpose and usage as the AsShotICCProfile and AsShotPreProfileMatrix tag pair, except they are for use by raw file editors rather than camera manufacturers. */                                                          
#define Exif.Image.CurrentPreProfileMatrix 0xc692          /* ImageSRationalThis tag is used in conjunction with the CurrentICCProfile tag. The CurrentICCProfile and CurrentPreProfileMatrix tags have the same purpose and usage as the AsShotICCProfile and AsShotPreProfileMatrix tag pair, except they are for use by raw file editors rather than camera manufacturers. */                                                                
#define Exif.Image.ColorimetricReference 0xc6bf            /* ImageShortThe DNG color model documents a transform between camera colors and CIE XYZ values. This tag describes the colorimetric reference for the CIE XYZ values. 0 = The XYZ values are scene-referred. 1 = The XYZ values are output-referred, using the ICC profile perceptual dynamic range. This tag allows output-referred data to be stored in DNG files and still processed correctly by DNG readers. */                         
#define Exif.Image.CameraCalibrationSignature 0xc6f3       /* ImageByteA UTF-8 encoded string associated with the CameraCalibration1 and CameraCalibration2 tags. The CameraCalibration1 and CameraCalibration2 tags should only be used in the DNG color transform if the string stored in the CameraCalibrationSignature tag exactly matches the string stored in the ProfileCalibrationSignature tag for the selected camera profile. */                              
#define Exif.Image.ProfileCalibrationSignature 0xc6f4      /* ImageByteA UTF-8 encoded string associated with the camera profile tags. The CameraCalibration1 and CameraCalibration2 tags should only be used in the DNG color transfer if the string stored in the CameraCalibrationSignature tag exactly matches the string stored in the ProfileCalibrationSignature tag for the selected camera profile. */                               
#define Exif.Image.AsShotProfileName 0xc6f6                /* ImageByteA UTF-8 encoded string containing the name of the "as shot" camera profile, if any. */                     
#define Exif.Image.NoiseReductionApplied 0xc6f7            /* ImageRationalThis tag indicates how much noise reduction has been applied to the raw data on a scale of 0.0 to 1.0. A 0.0 value indicates that no noise reduction has been applied. A 1.0 value indicates that the "ideal" amount of noise reduction has been applied, i.e. that the DNG reader should not apply additional noise reduction by default. A value of 0/0 indicates that this parameter is unknown. */                         
#define Exif.Image.ProfileName 0xc6f8                      /* ImageByteA UTF-8 encoded string containing the name of the camera profile. This tag is optional if there is only a single camera profile stored in the file but is required for all camera profiles if there is more than one camera profile stored in the file. */               
#define Exif.Image.ProfileHueSatMapDims 0xc6f9             /* ImageLongThis tag specifies the number of input samples in each dimension of the hue/saturation/value mapping tables. The data for these tables are stored in ProfileHueSatMapData1 and ProfileHueSatMapData2 tags. The most common case has ValueDivisions equal to 1, so only hue and saturation are used as inputs to the mapping table. */                        
#define Exif.Image.ProfileHueSatMapData1 0xc6fa            /* ImageFloatThis tag contains the data for the first hue/saturation/value mapping table. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees; the second entry is saturation scale factor; and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0. */                         
#define Exif.Image.ProfileHueSatMapData2 0xc6fb            /* ImageFloatThis tag contains the data for the second hue/saturation/value mapping table. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees; the second entry is a saturation scale factor; and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0. */                         
#define Exif.Image.ProfileToneCurve 0xc6fc                 /* ImageFloatThis tag contains a default tone curve that can be applied while processing the image as a starting point for user adjustments. The curve is specified as a list of 32-bit IEEE floating-point value pairs in linear gamma. Each sample has an input value in the range of 0.0 to 1.0, and an output value in the range of 0.0 to 1.0. The first sample is required to be (0.0, 0.0), and the last sample is required to be (1.0, 1.0). Interpolated the curve using a cubic spline. */                    
#define Exif.Image.ProfileEmbedPolicy 0xc6fd               /* ImageLongThis tag contains information about the usage rules for the associated camera profile. */                      
#define Exif.Image.ProfileCopyright 0xc6fe                 /* ImageByteA UTF-8 encoded string containing the copyright information for the camera profile. This string always should be preserved along with the other camera profile tags. */                    
#define Exif.Image.ForwardMatrix1 0xc714                   /* ImageSRationalThis tag defines a matrix that maps white balanced camera colors to XYZ D50 colors. */                  
#define Exif.Image.ForwardMatrix2 0xc715                   /* ImageSRationalThis tag defines a matrix that maps white balanced camera colors to XYZ D50 colors. */                  
#define Exif.Image.PreviewApplicationName 0xc716           /* ImageByteA UTF-8 encoded string containing the name of the application that created the preview stored in the IFD. */                                                               
#define Exif.Image.PreviewApplicationVersion 0xc717        /* ImageByteA UTF-8 encoded string containing the version number of the application that created the preview stored in the IFD. */                                                                  
#define Exif.Image.PreviewSettingsName 0xc718              /* ImageByteA UTF-8 encoded string containing the name of the conversion settings (for example, snapshot name) used for the preview stored in the IFD. */                       
#define Exif.Image.PreviewSettingsDigest 0xc719            /* ImageByteA unique ID of the conversion settings (for example, MD5 digest) used to render the preview stored in the IFD. */                                                              
#define Exif.Image.PreviewColorSpace 0xc71a                /* ImageLongThis tag specifies the color space in which the rendered preview in this IFD is stored. The default value for this tag is sRGB for color previews and Gray Gamma 2.2 for monochrome previews. */                     
#define Exif.Image.PreviewDateTime 0xc71b                  /* ImageAsciiThis tag is an ASCII string containing the name of the date/time at which the preview stored in the IFD was rendered. The date/time is encoded using ISO 8601 format. */                   
#define Exif.Image.RawImageDigest 0xc71c                   /* ImageUndefinedThis tag is an MD5 digest of the raw image data. All pixels in the image are processed in row-scan order. Each pixel is zero padded to 16 or 32 bits deep (16-bit for data less than or equal to 16 bits deep, 32-bit otherwise). The data for each pixel is processed in little-endian byte order. */                  
#define Exif.Image.OriginalRawFileDigest 0xc71d            /* ImageUndefinedThis tag is an MD5 digest of the data stored in the OriginalRawFileData tag. */                         
#define Exif.Image.SubTileBlockSize 0xc71e                 /* ImageLongNormally, the pixels within a tile are stored in simple row-scan order. This tag specifies that the pixels within a tile should be grouped first into rectangular blocks of the specified size. These blocks are stored in row-scan order. Within each block, the pixels are stored in row-scan order. The use of a non-default value for this tag requires setting the DNGBackwardVersion tag to at least 1.2.0.0. */                    
#define Exif.Image.RowInterleaveFactor 0xc71f              /* ImageLongThis tag specifies that rows of the image are stored in interleaved order. The value of the tag specifies the number of interleaved fields. The use of a non-default value for this tag requires setting the DNGBackwardVersion tag to at least 1.2.0.0. */                       
#define Exif.Image.ProfileLookTableDims 0xc725             /* ImageLongThis tag specifies the number of input samples in each dimension of a default "look" table. The data for this table is stored in the ProfileLookTableData tag. */                        
#define Exif.Image.ProfileLookTableData 0xc726             /* ImageFloatThis tag contains a default "look" table that can be applied while processing the image as a starting point for user adjustment. This table uses the same format as the tables stored in the ProfileHueSatMapData1 and ProfileHueSatMapData2 tags, and is applied in the same color space. However, it should be applied later in the processing pipe, after any exposure compensation and/or fill light stages, but before any tone curve stage. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees, the second entry is a saturation scale factor, and the third entry is a value scale factor. The table entries are stored in the tag in nested loop order, with the value divisions in the outer loop, the hue divisions in the middle loop, and the saturation divisions in the inner loop. All zero input saturation entries are required to have a value scale factor of 1.0. */                        
#define Exif.Image.OpcodeList1 0xc740                      /* ImageUndefinedSpecifies the list of opcodes that should be applied to the raw image, as read directly from the file. */               
#define Exif.Image.OpcodeList2 0xc741                      /* ImageUndefinedSpecifies the list of opcodes that should be applied to the raw image, just after it has been mapped to linear reference values. */               
#define Exif.Image.OpcodeList3 0xc74e                      /* ImageUndefinedSpecifies the list of opcodes that should be applied to the raw image, just after it has been demosaiced. */               
#define Exif.Image.NoiseProfile 0xc761                     /* ImageDoubleNoiseProfile describes the amount of noise in a raw image. Specifically, this tag models the amount of signal-dependent photon (shot) noise and signal-independent sensor readout noise, two common sources of noise in raw images. The model assumes that the noise is white and spatially independent, ignoring fixed pattern effects and other sources of noise (e.g., pixel response non-uniformity, spatially-dependent thermal effects, etc.). */                
